// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

export class MapData {
    /**
     * Creates a new MapData instance.
     * @param {Partial<MapData>} [$$source = {}] - The source object to create the MapData.
     */
    constructor($$source = {}) {
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("grid" in $$source)) {
            /**
             * @member
             * @type {number[][]}
             */
            this["grid"] = [];
        }
        if (!("startPoint" in $$source)) {
            /**
             * @member
             * @type {PointData}
             */
            this["startPoint"] = (new PointData());
        }
        if (!("endPoint" in $$source)) {
            /**
             * @member
             * @type {PointData}
             */
            this["endPoint"] = (new PointData());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MapData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MapData}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("grid" in $$parsedSource) {
            $$parsedSource["grid"] = $$createField2_0($$parsedSource["grid"]);
        }
        if ("startPoint" in $$parsedSource) {
            $$parsedSource["startPoint"] = $$createField3_0($$parsedSource["startPoint"]);
        }
        if ("endPoint" in $$parsedSource) {
            $$parsedSource["endPoint"] = $$createField4_0($$parsedSource["endPoint"]);
        }
        return new MapData(/** @type {Partial<MapData>} */($$parsedSource));
    }
}

export class MapInfoData {
    /**
     * Creates a new MapInfoData instance.
     * @param {Partial<MapInfoData>} [$$source = {}] - The source object to create the MapInfoData.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("modifiedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["modifiedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MapInfoData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MapInfoData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MapInfoData(/** @type {Partial<MapInfoData>} */($$parsedSource));
    }
}

export class PointData {
    /**
     * Creates a new PointData instance.
     * @param {Partial<PointData>} [$$source = {}] - The source object to create the PointData.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PointData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PointData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PointData(/** @type {Partial<PointData>} */($$parsedSource));
    }
}

export class SearchResultData {
    /**
     * Creates a new SearchResultData instance.
     * @param {Partial<SearchResultData>} [$$source = {}] - The source object to create the SearchResultData.
     */
    constructor($$source = {}) {
        if (!("found" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["found"] = false;
        }
        if (!("distance" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["distance"] = 0;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {PointData[]}
             */
            this["path"] = [];
        }
        if (!("algorithm" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["algorithm"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResultData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchResultData}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("path" in $$parsedSource) {
            $$parsedSource["path"] = $$createField2_0($$parsedSource["path"]);
        }
        return new SearchResultData(/** @type {Partial<SearchResultData>} */($$parsedSource));
    }
}

export class StepData {
    /**
     * Creates a new StepData instance.
     * @param {Partial<StepData>} [$$source = {}] - The source object to create the StepData.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["state"] = 0;
        }
        if (!("current" in $$source)) {
            /**
             * @member
             * @type {PointData}
             */
            this["current"] = (new PointData());
        }
        if (!("neighbors" in $$source)) {
            /**
             * @member
             * @type {PointData[]}
             */
            this["neighbors"] = [];
        }
        if (!("added" in $$source)) {
            /**
             * @member
             * @type {PointData[]}
             */
            this["added"] = [];
        }
        if (!("pruned" in $$source)) {
            /**
             * @member
             * @type {PointData[]}
             */
            this["pruned"] = [];
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {PointData[]}
             */
            this["path"] = [];
        }
        if (!("visited" in $$source)) {
            /**
             * @member
             * @type {PointData[]}
             */
            this["visited"] = [];
        }
        if (!("distance" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["distance"] = 0;
        }
        if (!("expanded" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expanded"] = 0;
        }
        if (!("stepsTaken" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["stepsTaken"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StepData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StepData}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("current" in $$parsedSource) {
            $$parsedSource["current"] = $$createField1_0($$parsedSource["current"]);
        }
        if ("neighbors" in $$parsedSource) {
            $$parsedSource["neighbors"] = $$createField2_0($$parsedSource["neighbors"]);
        }
        if ("added" in $$parsedSource) {
            $$parsedSource["added"] = $$createField3_0($$parsedSource["added"]);
        }
        if ("pruned" in $$parsedSource) {
            $$parsedSource["pruned"] = $$createField4_0($$parsedSource["pruned"]);
        }
        if ("path" in $$parsedSource) {
            $$parsedSource["path"] = $$createField5_0($$parsedSource["path"]);
        }
        if ("visited" in $$parsedSource) {
            $$parsedSource["visited"] = $$createField6_0($$parsedSource["visited"]);
        }
        return new StepData(/** @type {Partial<StepData>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = PointData.createFrom;
const $$createType3 = $Create.Array($$createType2);
