// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<$models.MapData | null>}
 */
export function CreateMap(width, height) {
    return $Call.ByID(3417669109, width, height).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteMap(name) {
    return $Call.ByID(3068171528, name);
}

/**
 * @returns {$CancellablePromise<$models.PointData[]>}
 */
export function GetCurrentPath() {
    return $Call.ByID(581338659).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<number[][]>}
 */
export function GetDraw() {
    return $Call.ByID(1089666905).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<number[][]>}
 */
export function GetFinalDraw() {
    return $Call.ByID(983372799).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.MapData | null>}
 */
export function GetMap() {
    return $Call.ByID(4225276827).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.SearchResultData | null>}
 */
export function GetSearchResult() {
    return $Call.ByID(440170618).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetStoragePath() {
    return $Call.ByID(3188186895);
}

/**
 * @param {string} algorithm
 * @returns {$CancellablePromise<void>}
 */
export function InitializeSearch(algorithm) {
    return $Call.ByID(292120495, algorithm);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsSearchDone() {
    return $Call.ByID(222894433);
}

/**
 * @returns {$CancellablePromise<$models.MapInfoData[]>}
 */
export function ListMaps() {
    return $Call.ByID(3096642454).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {$models.MapData | null} mapData
 * @returns {$CancellablePromise<void>}
 */
export function LoadMap(mapData) {
    return $Call.ByID(359228273, mapData);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<$models.MapData | null>}
 */
export function LoadMapByName(name) {
    return $Call.ByID(364452403, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function SaveMap(name) {
    return $Call.ByID(1000877058, name);
}

/**
 * @returns {$CancellablePromise<$models.StepData | null>}
 */
export function SearchStep() {
    return $Call.ByID(3162472031).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @param {number} x
 * @param {number} y
 * @param {number} cellType
 * @returns {$CancellablePromise<void>}
 */
export function SetCell(x, y, cellType) {
    return $Call.ByID(1178090979, x, y, cellType);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SetStoragePath(path) {
    return $Call.ByID(1009462627, path);
}

// Private type creation functions
const $$createType0 = $models.MapData.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.PointData.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.SearchResultData.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.MapInfoData.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.StepData.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
